### ISSUE TITLE
Infinite error loop after sign out

### ISSUE THREAD

**Issue by cowjen01** [aws-amplify/maplibre-gl-js-amplify#190]
Hello, I'm using @aws-amplify/ui-react `Authenticator` component together with the `MapView` component. After signing out using the built-in strategy I get an infinite error loop saying:

```
[DEBUG] 37:23.411 AuthClass - Failed to get user from user pool
ConsoleLogger.js:96 [DEBUG] 37:23.411 AuthClass - Failed to get the current user No current user
ConsoleLogger.js:86 [DEBUG] 37:23.411 AuthClass - getting guest credentials
ConsoleLogger.js:86 [DEBUG] 37:23.411 Credentials - setting credentials for guest
fetch-http-handler.js:47          POST https://cognito-identity.eu-west-1.amazonaws.com/ 400
ConsoleLogger.js:96 [DEBUG] 37:23.470 Credentials - Failed to load credentials Promise {<rejected>: NotAuthorizedException: Unauthenticated access is not supported for this identity pool.
    at http…}
ConsoleLogger.js:96 [DEBUG] 37:23.470 Credentials - Error loading credentials NotAuthorizedException: Unauthenticated access is not supported for this identity pool.
    at http://localhost:3000/static/js/bundle.js:53636:62
    at step (http://localhost:3000/static/js/bundle.js:244523:17)
    at Object.next (http://localhost:3000/static/js/bundle.js:244472:14)
    at fulfilled (http://localhost:3000/static/js/bundle.js:244431:24)
```

I found out there is a loop trying the refresh the credentials after sign out:

```js
Hub.listen("auth", (data) => {
      switch (data.payload.event) {
        case "signIn":
        case "signOut":
        case "tokenRefresh":
          this.refreshCredentialsWithRetry();
          break;
      }
    });

...

refreshCredentialsWithRetry = async (): Promise<void> => {
    try {
      const MAX_DELAY_MS = 5 * 60 * 1000; // 5 minutes
      await jitteredExponentialRetry(this.refreshCredentials, [], MAX_DELAY_MS);
...
```

The errors are repeating until I refresh browser. Do you know how to solve this issue or at least what walk-around I could use to avoid the loop? Thanks!

**Comment by 0618** [comment]
duplicated with https://github.com/aws-amplify/amplify-ui/issues/3367
