### ISSUE TITLE
the map is not loading 

### ISSUE THREAD

**Issue by abhirpat** [aws-amplify/maplibre-gl-js-amplify#225]
I am getting below error in browser console maplibre-gl-js-amplify 3.1.0 using version 2.4.0 of maplibre-gl
605dc0a9-69a1-4cd8-9f0c-cf4a2d32bec9:1 
Uncaught ReferenceError: g is not defined

 If I change version to 1.5.3, the map will load fine however it crashes when using "drawPoints" from "maplibre-gl-js-amplify".
 
 main.74261051.js:2 Error: There is already a source with this ID
    at r.addSource (main.74261051.js:2:1199380)
    at i.addSource (main.74261051.js:2:1400678)
    at kE (main.74261051.js:2:5884418)
    at main.74261051.js:2:5889520
    at ls (main.74261051.js:2:1631845)
    at Pu (main.74261051.js:2:1650819)
    at t.unstable_runWithPriority (main.74261051.js:2:1677438)
    at Qi (main.74261051.js:2:1593465)
    at wu (main.74261051.js:2:1650570)
    at main.74261051.js:2:1650481

**Comment by zchenwei** [comment]
Hi @abhirpat, as far as I know `maplibre-gl-js-amplify` is meant for internal use only. If you want to use something from `maplibre-gl`, you should go ahead use the exports from within itself.

**Comment by abhirpat** [comment]
I resolved the issue. We are good.
